// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// SIM
Rcpp::List SIM(int nMin, int nMax, arma::vec nByVec, double phi, double targetDelta, arma::vec block0, double enr_mn, double enr_sd, double asc_mn, double asc_sd, double skp_mn, double true_sd, arma::vec true_mn, double hst_n, double hst_mn, double hst_sd, int nSims, int nSamp);
RcppExport SEXP _trialsimulation_SIM(SEXP nMinSEXP, SEXP nMaxSEXP, SEXP nByVecSEXP, SEXP phiSEXP, SEXP targetDeltaSEXP, SEXP block0SEXP, SEXP enr_mnSEXP, SEXP enr_sdSEXP, SEXP asc_mnSEXP, SEXP asc_sdSEXP, SEXP skp_mnSEXP, SEXP true_sdSEXP, SEXP true_mnSEXP, SEXP hst_nSEXP, SEXP hst_mnSEXP, SEXP hst_sdSEXP, SEXP nSimsSEXP, SEXP nSampSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nMin(nMinSEXP);
    Rcpp::traits::input_parameter< int >::type nMax(nMaxSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nByVec(nByVecSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type targetDelta(targetDeltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type block0(block0SEXP);
    Rcpp::traits::input_parameter< double >::type enr_mn(enr_mnSEXP);
    Rcpp::traits::input_parameter< double >::type enr_sd(enr_sdSEXP);
    Rcpp::traits::input_parameter< double >::type asc_mn(asc_mnSEXP);
    Rcpp::traits::input_parameter< double >::type asc_sd(asc_sdSEXP);
    Rcpp::traits::input_parameter< double >::type skp_mn(skp_mnSEXP);
    Rcpp::traits::input_parameter< double >::type true_sd(true_sdSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type true_mn(true_mnSEXP);
    Rcpp::traits::input_parameter< double >::type hst_n(hst_nSEXP);
    Rcpp::traits::input_parameter< double >::type hst_mn(hst_mnSEXP);
    Rcpp::traits::input_parameter< double >::type hst_sd(hst_sdSEXP);
    Rcpp::traits::input_parameter< int >::type nSims(nSimsSEXP);
    Rcpp::traits::input_parameter< int >::type nSamp(nSampSEXP);
    rcpp_result_gen = Rcpp::wrap(SIM(nMin, nMax, nByVec, phi, targetDelta, block0, enr_mn, enr_sd, asc_mn, asc_sd, skp_mn, true_sd, true_mn, hst_n, hst_mn, hst_sd, nSims, nSamp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_trialsimulation_SIM", (DL_FUNC) &_trialsimulation_SIM, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_trialsimulation(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
